apiVersion: apps/v1
kind: Deployment
metadata:
  name: -manager
  namespace: -system
  labels:
    control-plane: dcontroller
spec:
  selector:
    matchLabels:
      control-plane: dcontroller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: dcontroller
      labels:
        control-plane: dcontroller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /dbsp
        args:
        - /dcontroller/dcontroller.js
        image: dcontroller:latest
        name: dcontroller
        env:
        - name: DCONTROLLER_API_SERVER_ENABLED
          value: "true"
        - name: DCONTROLLER_API_SERVER_MODE
          value: "development"
        - name: DCONTROLLER_API_SERVER_ADDR
          value: "0.0.0.0"
        - name: DCONTROLLER_API_SERVER_PORT
          value: "8443"
        - name: DCONTROLLER_API_SERVER_HTTP
          value: "true"
        - name: DCONTROLLER_API_SERVER_INSECURE
          value: "true"
        ports:
        - name: api
          containerPort: 8443
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          tcpSocket:
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: dcontroller-account
      terminationGracePeriodSeconds: 10
