# operator that stores pods in a view to avoid the envtest API server messing with our pod status
apiVersion: dcontroller.io/v1alpha1
kind: Operator
metadata:
  name: svc-health-operator
spec:
  sources:
    - kind: PodView
    - apiGroup: ""
      kind: Service
  circuits:
    - name: pod-health-monitor
      inputs: [PodView]
      outputs: [HealthView]
      pipeline:
        - "@project":
            metadata:
              name: "$.metadata.labels.app"
              namespace: "$.metadata.namespace"
            pods:
              podName: "$.metadata.name"
              ready: "$.status.conditions[?(@.type=='Ready')].status"
        - "@groupBy":
            - "$.metadata"
            - "$.pods"
        - "@project":
            metadata: "$.key"
            pods: "$.values"
      transforms:
        - name: Reconciler
        - name: Distincter
        - name: Incrementalizer

    # HealthView is an internal stream: produced by the first circuit,
    # consumed by the second, bound to nothing.
    - name: svc-health-monitor
      inputs: [HealthView, Service]
      outputs: [ServiceHealth]
      pipeline:
        - "@join":
            "@and":
              - "@eq": ["$.HealthView.metadata.name", "$.Service.metadata.name"]
              - "@eq": ["$.HealthView.metadata.namespace", "$.Service.metadata.namespace"]
        - "@project":
              metadata:
                name: "$.Service.metadata.name"
                namespace: "$.Service.metadata.namespace"
                annotations:
                  "dcontroller.io/pod-ready":
                    "@concat":
                      - "@string":
                          "@len":
                            "@filter":
                              - "@eq": ["$$.ready", "True"]
                              - "$.HealthView.pods"
                      - "/"
                      - "@string":
                          "@len": "$.HealthView.pods"
      transforms:
        - name: Reconciler
        - name: Distincter
        - name: Incrementalizer
  targets:
    - apiGroup: ""
      kind: Service
      type: Patcher
      as: ServiceHealth
