apiVersion: v2
name: dcontroller
description: Delta-controller, a declarative incremental Kubernetes controller runtime built on DBSP
type: application
version: 0.0.0
appVersion: latest
home: https://github.com/l7mp/dbsp
sources:
  - https://github.com/l7mp/dbsp
keywords:
  - kubernetes
  - controller
  - operator
  - incremental
  - dbsp
maintainers:
  - name: rg0now
